name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: byronogis/workflows/.github/workflows/release.yml@v1
    with:
      publish: nr publish
      build: nr build
    permissions:
      contents: write
      id-token: write
