name: Setup JavaScript environment
author: Byron
description: Setup JavaScript environment

inputs:
  checkout_persist-credentials:
    description: Whether to configure the token or SSH key with the local git config. Defaults to false.
    required: false
    default: 'false'

  checkout_fetch-depth:
    description: Number of commits to fetch. 0 indicates all history for all branches and tags. Defaults to 1.
    required: false
    default: '1'

  runtime:
    description: 'Runtime to setup. Examples: node, deno, bun. Default is node.'
    required: false
    default: node

  runtime-version:
    description: 'Version Spec of the runtime to use. Defaults: for Node is lts/*, for Deno is lts, for Bun is latest.'
    required: false

  node-package-manager:
    description: 'Package manager to use when runtime is node. Examples: npm, yarn, pnpm. Default is pnpm.'
    required: false
    default: pnpm

  auto-install:
    description: Whether to automatically install dependencies. Defaults to true.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        persist-credentials: ${{ inputs.checkout_persist-credentials == 'true' }}
        fetch-depth: '${{ inputs.checkout_fetch-depth }}'

    - name: Prepare corepack
      shell: bash
      run: npm install -g corepack@latest --force

    - name: Prepare ni (use the right package manager)
      shell: bash
      run: npm install -g @antfu/ni@latest

    - name: Setup node
      if: ${{ inputs.runtime == 'node' }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.runtime-version || 'lts/*' }}
        registry-url: 'https://registry.npmjs.org'
        cache: ${{ inputs.node-package-manager }}

    - name: Setup deno
      if: ${{ inputs.runtime == 'deno' }}
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ inputs.runtime-version || 'lts' }}

    - name: Setup bun
      if: ${{ inputs.runtime == 'bun' }}
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.runtime-version || 'latest' }}

    - name: Install dependencies
      if: ${{ inputs.auto-install == 'true' }}
      shell: bash
      run: ni
      env:
        NI_DEFAULT_AGENT: ${{ inputs.runtime == 'node' && inputs.node-package-manager || inputs.runtime }}
